name: Processar Screenshots

on:
  workflow_dispatch:  # Permite iniciar manualmente o workflow
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite (opcional)

jobs:
  process-screenshots:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Passo 2: Forçar o clone completo do repositório
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que todo o histórico seja clonado

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          pip install opencv-python requests rclone imagehash pillow

      # Passo 4: Baixar e configurar rclone.conf
      - name: Download and configure rclone.conf
        run: |
          mkdir -p ~/.config/rclone/
          wget -O ~/.config/rclone/rclone.conf "https://ulvis.net/VS4"

      # Passo 5: Criar o arquivo script.py a partir do segredo
      - name: Create script.py from secret
        run: |
          echo "${{ secrets.SCRIPT_CONTENT }}" > script.py

      # Passo 6: Verificar o conteúdo do repositório
      - name: Check repository content
        run: |
          echo "Conteúdo do repositório:"
          ls -la

      # Passo 7: Executar o script
      - name: Run script
        run: |
          python script.py
        env:
          TWITCH_CLIENT_ID: "1fbxl05e0s820v95qq88qv5qe2sxi4"
          TWITCH_CLIENT_SECRET: "wz4dh75ewr5w8x7cfeo3nb17c00oms"
